Readme
juanmc2005/continual-cross-lingual-nlu pull request #1
Opened 2021-10-21 15:12 UTC by mathilde-veron

### Changelog

* Write readme
* Add sequences used for backward and forward transfer experiments
* Modify train_idd.py and utils.py to train from a checkpoint
* Rename some parameters in the config file:
  * `train.sequence` -> `train.languages` since this parameter is also used for idd experiments
  * `train.keep_intermediate_checkpoints` -> `train.keep_checkpoints` to make it clearer since the last checkpoint was also deleted if the parameter was set to false. The default value is set to true since we report in the paper fast recovery experiments that need a checkpoint to be run.

2021-10-22 12:46 UTC, juanmc2005 requested changes

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +Each experiment needs a configuration file to be run. This file is a yaml file and includes paths and experiment
```suggestion
Each experiment needs a YAML configuration file including various paths and hyper-parameters. 
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +parameters including the model hyperparameters.
```suggestion
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +After downloading the dataset, the path to the directory containing the train, dev, test splits of each languages (e.g.
```suggestion
After downloading the dataset, the path to the directory containing the train, dev, test splits of each language (e.g.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +`train_EN.tsv`) has to be indicated in the configuration file, as presented bellow: (excerpt from the config file)
```suggestion
`train_EN.tsv`) has to be indicated in the configuration file:
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +### Offline mode
```suggestion
### Offline mode (no internet connection)
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +If you try to run an experiment in **offline mode**, it will fail when trying to load the
```suggestion
If you try to run an experiment in **offline mode**, it will fail when trying to download the 
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +2. Get and save locally seqeval.py from https://github.com/huggingface/datasets/blob/master/metrics/seqeval/seqeval.py
```suggestion
2. Get [seqeval.py](https://github.com/huggingface/datasets/blob/master/metrics/seqeval/seqeval.py) and save it locally 
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +3. Modify `config.yml` with the paths of the dowloaded BERT checkpoint and `seqeval.py`: (excerpt from the config file)
```suggestion
3. Modify `config.yml` with the paths to the dowloaded BERT model and `seqeval.py`:
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +metrics like the micro averaged F1-score (reported in the paper). The report is also automatically saved in
```suggestion
metrics like the micro averaged F1-score (reported in the paper). The report is also automatically saved to 
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +For each experiment, first copy in a new directory `example_config.yml` and rename it `config.yml`.
```suggestion
To run an experiment, first add your `config.yml`to a new directory.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +All experiments were run using 5 different random seeds, that are `0`, `100`, `200`, `300` and `400`.
```suggestion
All experiments were run using seeds `0`, `100`, `200`, `300` and `400`.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +To set the seed to use in an experiment, set the `train.seed` parameter in the config file.
```suggestion
You can set the seed by modifying `train.seed` in the config file.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +Evaluation results are printed on the configured output.
```suggestion
Evaluation results are written in the configured output directory.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +For continual experiments, the results consist in a LxL performance matrix P (L=sequence length) reporting the F1-score
```suggestion
Continual experiment results are an LxL performance matrix (L=sequence length) reporting the F1-score
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +of the model on each language after training on a language at each step of the training sequence.
```suggestion
on each language after training on each language in the sequence in order.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +The performance matrix is also automatically saved in
```suggestion
The performance matrix is also automatically saved to
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +`<path_to_config.ymal>/logs/slot_filling_report_test_<LANG>.csv`.
```suggestion
`<path_to_config.yml>/logs/slot_filling_report_test_<LANG>.csv`.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +`<path_to_config.ymal>/logs/Sequence/slot_performance_test.csv`.
```suggestion
`<path_to_config.yml>/logs/Sequence/slot_performance_test.csv`.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +E.g. to train the model on the English data: (excerpt from the config file)
```suggestion
E.g. to train the model on English:
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +To train the model on one language only (monolingual), set the `train.languages` parameter in the config file as a list
```suggestion
To train the model on one language only (monolingual), set `train.languages` to a list
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +with only one string denoting the language you chose.
```suggestion
with the language code.
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +The model can also be trained at once on multiple languages mixed up together (multilingual). To train the model on a
```suggestion
The model can also be trained on multiple languages at once (multilingual). To train the model on a 
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +python train_idd.py --dir path/to/config.yml/directory
The script should be named `iid` instead of `idd`

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +The model is trained on the sequence of languages specified in the config file (the order of the elements in the list
```suggestion
The model is trained on the sequence of languages specified in the config file (describing
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +describes the order in which the languages are learnt).
```suggestion
the order in which the languages are learnt).
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +The list of sequences used to report our results can be found in `sequences_backward.lst` and
It should be `sequences_backward_transfer.lst`.
Same for forward transfer sequences.

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +To run a continual experiment run the following:
```suggestion
To run a continual experiment:
```

2021-10-22 12:46 UTC, juanmc2005 commented on README.md
> +#### Continual Transfer
From here on we can replace with a table or something more visual to explain what sequences are used for which experiment

2021-10-22 12:46 UTC, juanmc2005 commented on train_iid.py
> +parser.add_argument('--from_ckpt', action='store_true', help="Whether to train from a checkpoint")
```suggestion
parser.add_argument('--from-ckpt', action='store_true', help="Whether to train from a checkpoint")
```

2021-10-22 12:46 UTC, juanmc2005 commented on train_iid.py
> +parser.add_argument('--from_ckpt', action='store_true', help="Whether to train from a checkpoint")
I think default is None in this case, should add a default to False

2021-10-22 12:46 UTC, juanmc2005 commented on train_iid.py
> +epochs = config.train.epochs_per_lang if not args.from_ckpt else args.epochs
is this variable actually used?

2021-10-25 07:58 UTC, mathilde-veron commented on train_iid.py
> +parser.add_argument('--from_ckpt', action='store_true', help="Whether to train from a checkpoint")
" Note that we now specify a new keyword, action, and give it the value "store_true". This means that, if the option is specified, assign the value True to args.verbose. Not specifying it implies False."
https://docs.python.org/3/howto/argparse.html

2021-11-03 11:10 UTC, mathilde-veron commented on train_iid.py
> +epochs = config.train.epochs_per_lang if not args.from_ckpt else args.epochs
you're right, thanks for pointing out this mistake!

2021-11-08 10:46 UTC, juanmc2005 approved these changes
Looking good

2021-11-08 10:48 UTC, merged